### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by itzdrli** [kb-1000/JumpQuilt#1]
Forge version: `40.1.54`
Quilt used version: `0.17.1-beta6`
all mods are about fabric/quilt's
Error:
after a loading window with jumpquilt's logo and title, another new window with name `Quilt Loader 0.17.1-beta.6` shows an error:
![error sc](https://user-images.githubusercontent.com/52338732/177880970-33f84efd-c360-48e9-938c-2548e6418b69.png)
System: `Windows 10 21H2`
Minecraft version: `1.18.2`
I've run those mods without jumpquilt and everything is fine, then I removed Quilt and installed Forge.

**Comment by kb-1000** [comment]
Fixed in 2.2.0
