### ISSUE TITLE
Uncaught exception in thread "main"

### ISSUE THREAD

**Issue by Kamiszewskyy** [kb-1000/JumpQuilt#2]
![image](https://user-images.githubusercontent.com/62818516/181399082-9deb49a1-c6a9-4d36-9eab-531f498fdc2e.png)

**Comment by Kamiszewskyy** [comment]
![image](https://user-images.githubusercontent.com/62818516/181400454-05f68094-0f7f-4a1c-95a1-1181c3c28bb4.png)

**Comment by kb-1000** [comment]
Fixed in 2.3.0
